### ISSUE TITLE
I still wonder why people think it is a good idea to use matlab

### ISSUE THREAD

**Issue by rhighs** [MatteoIorio11/MetodiNumerici#1]

**Comment by MatteoIorio11** [comment]
I actually do not know why people think this, but here is a video where you can actually understand how MatLab changed the world : https://www.youtube.com/watch?v=dQw4w9WgXcQ
Let me know what you think about this

**Comment by rhighs** [comment]
Ouch! you got me there fella hehe
Next time try with [mathematica](https://www.youtube.com/watch?v=oHg5SJYRHA0), such a good language to start off with numerical methods

**Comment by MatteoIorio11** [comment]
I am going to report you for this, It is against the international laws ahahahahah
*emoticon of a person who is about to report a guy on GITHUB*
